using System;
using System.Collections.Generic;

namespace Carbon.Hooks;

#if RUST_STAGING || STAGING_HOOK_VERIFIER
internal enum StagingHookCompatAction
{
	Shim,
	GeneratorPolicyFix,
	DisabledObsolete
}

internal readonly struct StagingHookCompatEntry
{
	public StagingHookCompatEntry(string hookFullName, StagingHookCompatAction action, bool suppressGeneratedHook, string reason)
	{
		HookFullName = hookFullName;
		Action = action;
		SuppressGeneratedHook = suppressGeneratedHook;
		Reason = reason;
	}

	public string HookFullName { get; }
	public StagingHookCompatAction Action { get; }
	public bool SuppressGeneratedHook { get; }
	public string Reason { get; }
}

internal static class StagingHookCompatManifest
{
	private static readonly StagingHookCompatEntry[] Entries =
	{
		new("CanCastFishingRod", StagingHookCompatAction.GeneratorPolicyFix, false, "Generated by staging policy against BaseFishingRod.Server_RequestCast."),
		new("CanCatchFish", StagingHookCompatAction.GeneratorPolicyFix, false, "Generated by staging policy against BaseFishingRod.CatchProcessBudgeted."),
		new("OnFishCatch", StagingHookCompatAction.GeneratorPolicyFix, false, "Generated by staging policy against BaseFishingRod.CatchProcessBudgeted."),
		new("OnItemCraft", StagingHookCompatAction.GeneratorPolicyFix, false, "Generated by staging policy against ItemCrafter.CraftItem."),
		new("OnCorpsePopulate", StagingHookCompatAction.GeneratorPolicyFix, false, "Generated by staging policy against NPCPlayer.CreateCorpse."),
		new("OnPlayerVoice", StagingHookCompatAction.GeneratorPolicyFix, false, "Generated by staging policy against BasePlayer.OnReceivedVoice(ReadOnlySpan<byte>)."),
		new("OnDispenserGather", StagingHookCompatAction.GeneratorPolicyFix, false, "Generated by staging policy against ResourceDispenser.GiveResourceFromItem."),
		new("OnDispenserGathered", StagingHookCompatAction.GeneratorPolicyFix, false, "Generated by staging policy against ResourceDispenser.GiveResourceFromItem."),
		new("OnDispenserBonus", StagingHookCompatAction.GeneratorPolicyFix, false, "Generated by staging policy against ResourceDispenser.AssignFinishBonus."),
		new("OnDispenserBonusReceived", StagingHookCompatAction.GeneratorPolicyFix, false, "Generated by staging policy against ResourceDispenser.AssignFinishBonus."),
		new("OnCollectiblePickedup", StagingHookCompatAction.GeneratorPolicyFix, false, "Generated by staging policy against CollectibleEntity.DoPickup."),
		new("OnPlayerAttack [Projectile]", StagingHookCompatAction.GeneratorPolicyFix, false, "Generated by staging policy against BasePlayer.OnProjectileAttack."),
		new("OnPlayerAttack [Projectile] [Patch]", StagingHookCompatAction.GeneratorPolicyFix, false, "Generated as a no-op because the staging projectile policy owns cancellation."),
		new("FixItemKeyId [patch]", StagingHookCompatAction.GeneratorPolicyFix, false, "Generated as a no-op because staging ItemCrafter.CraftItem carries attachmentID natively."),
		new("NoLimboGroupForPlayers [patch]", StagingHookCompatAction.GeneratorPolicyFix, false, "Generated hook is verified against installed staging IL.")
	};

	private static readonly Dictionary<string, StagingHookCompatEntry> EntryByHookFullName = BuildIndex();

	public static IReadOnlyList<StagingHookCompatEntry> All => Entries;

	public static bool TryGet(string hookFullName, out StagingHookCompatEntry entry)
	{
		if (!string.IsNullOrEmpty(hookFullName) && EntryByHookFullName.TryGetValue(hookFullName, out entry))
		{
			return true;
		}

		entry = default;
		return false;
	}

	public static bool ShouldSuppressGeneratedHook(string hookFullName, out StagingHookCompatEntry entry)
	{
		return TryGet(hookFullName, out entry) && entry.SuppressGeneratedHook;
	}

	private static Dictionary<string, StagingHookCompatEntry> BuildIndex()
	{
		Dictionary<string, StagingHookCompatEntry> index = new(StringComparer.Ordinal);

		foreach (StagingHookCompatEntry entry in Entries)
		{
			index.Add(entry.HookFullName, entry);
		}

		return index;
	}
}
#endif
